replicaCount: 1

image:
  repository: ghcr.io/xgeekshq/snipsnap
  tag: latest
  pullPolicy: IfNotPresent

workspaceName: default

api:
  port: 8000

metrics:
  enabled: false
  bindAddress: ":8443"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: snipsnap-controller

nodeSelector: {}
tolerations: []
affinity: {}

models: []

# - name: qwen3-5-2b
#   url: "ollama://qwen3.5:2b"
#   engine: OLlama
#   cache:
#     enabled: true
#     storageSize: "5Gi"
#   resources:
#     limits:
#       nvidia.com/gpu: "1"
