replicaCount: 1

image:
  repository: ghcr.io/xgeekshq/snipsnap
  tag: latest
  pullPolicy: IfNotPresent

namespace: snipsnap

workspaceName: default

api:
  port: 8000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: true
  name: snipsnap-controller

nodeSelector: {}
tolerations: []
affinity: {}
