apiVersion: snipsnap.xgeeks.com/v1
kind: Model
metadata:
  name: qwen3-5-2b
spec:
  url: "ollama://qwen3.5:2b"
  engine: OLlama
  cache:
    enabled: true
    storageSize: "5Gi"
  resources:
    limits:
      nvidia.com/gpu: "1"
