apiVersion: snipsnap.xgeeks.com/v1
kind: Model
metadata:
  labels:
    app.kubernetes.io/name: snipsnap
    app.kubernetes.io/managed-by: kustomize
  name: model-sample
spec:
  # TODO(user): Add fields here
