{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: snipsnap-controller-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: snipsnap
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: snipsnap
    app.kubernetes.io/component: controller
{{- end }}
